name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Create directory on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} "mkdir -p /home/${{ secrets.EC2_USER }}/app"

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r * ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }}:/home/${{ secrets.EC2_USER }}/app

      - name: Install dependencies and start FastAPI
        run: |
          run: |
  ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
    # Navegar al directorio de la aplicación
    cd /home/${{ secrets.EC2_USER }}/app
    
    # Actualizar el repositorio (si está versionado con git)
    git pull origin main
    
    # Crear un entorno virtual si no existe
    python3 -m venv venv
    
    # Activar el entorno virtual
    source venv/bin/activate
    
    # Instalar dependencias
    pip install -r requirements.txt
    
    # Finalizar cualquier instancia de la aplicación en ejecución
    pkill -f "uvicorn main:app" || true
    
    # Ejecutar la aplicación en segundo plano con nohup y guardar logs
    nohup uvicorn main:app --host 0.0.0.0 --port 80 > app.log 2>&1 &
    
    # Verificar que la aplicación esté en ejecución
    sleep 5
    if pgrep -f "uvicorn main:app"; then
      echo "La aplicación está corriendo correctamente"
    else
      echo "Hubo un problema al iniciar la aplicación" >&2
      exit 1
    fi
  EOF

